module8-task2
htmlacademy-javascript/2003613-keksobooking-25 pull request #10
Opened 2022-03-28 07:16 UTC by Arty-Petrov

Пофиксил код по комментариям к предыдущим задачам.
Синхронизация полей Тип жилья и Время заезда /  выезда уже были реализованы в задаче module8-task1.

2022-03-31 08:23 UTC, Dima-Dim requested changes

2022-03-31 08:23 UTC, Dima-Dim commented on js/form-validate.js
>    } else if (symbolsCount < 30) {
https://up.htmlacademy.ru/javascript/25/criteries#d15

2022-04-01 09:14 UTC, Arty-Petrov commented on js/form-validate.js
>    } else if (symbolsCount < 30) {
Не понял комментарий. В Д15 указано, что если в любом случае возвращается значение то ветка не нужна, здесь по другому.  Задача  данного участка кода— отсеять ошибки, если критерии не соблюдаются, то ничего и не возвращается. Единственное, что я поправил бы — это if (!symbolsCount) заменил бы на явное сравнение с нулем.

2022-04-01 11:38 UTC, Dima-Dim commented on js/form-validate.js
>    } else if (symbolsCount < 30) {
`if` убирать не нужно, а вот в `else` после `return` смысла нет.

2022-04-02 14:55 UTC, merged