Module2 task1
htmlacademy-javascript/2003613-keksobooking-25 pull request #4
Opened 2022-02-23 05:55 UTC by Arty-Petrov

2022-02-24 08:17 UTC, Dima-Dim requested changes

2022-02-24 08:17 UTC, Dima-Dim commented on index.html
> +            <input type="checkbox" name="features" value="dishwasher" id="filter-dishwasher"
По хаданию в этой части разметке нет каких либо правок.

2022-02-24 08:17 UTC, Dima-Dim commented on js/main.js
> +  const MIN_VAL = minRangeValue;
Это не константа в плане нейминга, потому что она зависит от переданного в функцию значения. Но задаётся оно через const.

2022-02-24 08:17 UTC, Dima-Dim commented on js/main.js
> +  const ERROR_MESSAGE = console.log;
Нет в этом особого смысла :) Ещё и нарушает критерий об именовании функций. И если это для вывода ошибок, то console.error

2022-02-24 08:20 UTC, Arty-Petrov commented on index.html
> +            <input type="checkbox" name="features" value="dishwasher" id="filter-dishwasher"
Второй элемент списка в разделе "Подготовка":
"В директории /js вашего проекта расположен пустой файл main.js. **Подключите его в файле index.html** и выполняйте задание в нём."
Ровно то и сделал. Не нужно было?

2022-02-24 08:23 UTC, Arty-Petrov commented on js/main.js
> +  const MIN_VAL = minRangeValue;
То есть получается так:
нужно помечать глобальные константы, а то что локальные внутри блоков просто camelCase
Спасибо, поправлю

2022-02-24 08:23 UTC, Arty-Petrov commented on js/main.js
> +  const ERROR_MESSAGE = console.log;
Принял, сделаю

2022-02-24 08:25 UTC, Dima-Dim commented on index.html
> +            <input type="checkbox" name="features" value="dishwasher" id="filter-dishwasher"
Я про изменения в разметке. Нет же в задании ничего про форматирование html разметки?

2022-02-24 08:27 UTC, Dima-Dim commented on js/main.js
> +  const MIN_VAL = minRangeValue;
Если бы внутри функции было:
`  const MIN_VAL = 5;` - то это было бы верно, но у тебя есть зависимость, т.е. в `MIN_VAL` не всегда одно и тоже значение.

2022-02-24 08:30 UTC, Arty-Petrov commented on index.html
> +            <input type="checkbox" name="features" value="dishwasher" id="filter-dishwasher"
ААА понял, это видимо ручонки шаловливые :-)

2022-02-24 08:42 UTC, Arty-Petrov commented on js/main.js
> +  const ERROR_MESSAGE = console.log;
console.error линтер подсветил как нежелательный элемент. Если не консолью, то как еще можно дать знать о характере ошибки? У меня есть мысль только про try-catch, но мы это еще не проходили :-)

2022-02-24 11:17 UTC, Dima-Dim commented on js/main.js
> +  const ERROR_MESSAGE = console.log;
Ещё можно `throw new Error();` :)

2022-02-26 13:23 UTC, Dima-Dim commented on index.html
> +            <input type="checkbox" name="features" value="dishwasher" id="filter-dishwasher"
Нужно вернуть этот участок к прежнему состоянию :)

2022-02-26 15:03 UTC, merged